### PR TITLE
Patch 10 Update "strings.xml" 0.7.3

### PR DESCRIPTION
**Pull request by H-F-M**

### CODE REVIEW

**Comment by tateisu** [comment]
```
<string name="plugin_not_installed">Aucun plugin emoji n\'est installé.\n(EmojionePicker est disponible gratuitement sur GooglePlay).</string>
```
Mushroom plugin is NOT only for emoji.

there is many many mushroom apps on play store.
search-mushroom

But "showing guide to some plugin app" is good idea.

maybe the message that shown when no plugin installed is like such as:
```
No input  plugins are installed.
Recommended plugins:   (on Google Play Store)
EmojionePicker https://play.google.com/store/apps/details?id=com.mastopane.emojionepicker
SupportText Free https://play.google.com/store/apps/details?id=com.z589.supporttext
ANdClip Free Https://play.google.com/store/apps/details?id=com.amazing_create.android.andclipfree
Contact Picker Https://play.google.com/store/apps/details?id=jp.narikitic.android.mushroom.contactPicker
顔文字コピー https://play.google.com/store/apps/details?id=jp.neoscorp.android.kaomoji
```
(and  make link clickable)
Can you check these app is available in your region ?
Can you find some recommend app and list its title and play-store url ?

**Comment by tateisu** [comment]
I have to describe about "Custom Notification Listener" to you.

Notification Listener is used to real-time notification.
- Notification Listener is a server that received user's access token and connect Streaming API on Mastodon instance.
- when it receives notification, it callbacks to Subway Tooter's app server with notification detail.
- Subway Tooter's app server send it via Firebase Cloud Messaging and it dispatched to user's device.
- user's device dispatch the message to app, then app can show notification in nearly real-time.

In default. Subway Tooter's app server knows very few Notification Listener server those are provided by instance-owner.

I've added app setting that user can specify the Notification Listener server and password to connect it.
I thought this is a function for a very limited user who can make Notification Listener server himself,
but some volunteers have built Notification Listener server and started sharing its configuration information among users.

(A mechanism to distribute server burden among volunteers has been created ?)

(I think maybe using shared Notification Listener has Security problem. The owner of Notification Listener can read DM...)

This is example of shared Notification Listener server.
https://md.ggtea.org/skrnotifier.html

```
<string name="secret">Code</string>
```

Please don't translate 'Secret' to 'Code'.
- This word came from the name of configuration parameter of Notification Listener server. I don't want to confuse the user who build Notification Listener server and use it for private.

**Comment by H-F-M** [comment]
Hi,
All plugin previously mentioned are avaiable in my country. Some of these
are only in Japanes language (description), and it's really hard to
European people to understand functionality (cause google translate does
not make good work between Japanese and French or dutsh or other (except
for English, so i allways choose Jap/Eng for understanding your update
notifications).

Good idea to put clickable links (like referance to explain the
possibilities of bouquets of mushrooms). If possible, not only when there
are not already present.

I will try to find some usefull other plugins.


2017-05-27 18:12 GMT+02:00 tateisu <notifications@github.com>:

**Comment by H-F-M** [comment]
Ok, changed in strings.xml, and thanks for explanation about "Custom Notification Listener".

**Comment by H-F-M** [comment]
Mushroom plugins are not very popular here, there are many made by Japanese
and generally they all turn around emojis, useful plugins are really rare
or everything is in Japanese. They are mainly made to use Twicca or Simeji
and are not recognized by Subway Tooter.

I could only find four that are of questionable utility but I could not do
better.
I saw that you had develloped some that look useful, you should put them in
your list.

AntiSearchEngine v1.0.0b19
https://play.google.com/store/apps/details?id=jp.Keshigoto.AntiSearchEngine&hl=fr
Emoji Mush v1.4b21
https://play.google.com/store/apps/details?id=jp.mstssk.emoji_mush&hl=fr
Facemark Generator Mushroom v1.1b4
https://play.google.com/store/apps/details?id=jp.rgfx_currentdir_ozero.facegenmush&hl=fr
Tagifier v1.0.1b21
https://play.google.com/store/apps/details?id=jp.wktk.tagifier&hl=fr

All tested with Subway Tooter and work well.

2017-05-27 19:34 GMT+02:00 H.ide.F.M <cittaul@gmail.com>:

**Comment by tateisu** [comment]
Thanks!  I'll make dialog for recommended plugin for fr,en,ja.

**Comment by tateisu** [comment]
it will be included on v0.7.4

this dialog is shown when plugin is not installed, or tap "Recommended Plugin" on "more" menu.
If you want change plugin list, please find app/src/main/res/raw .
device-2017-05-28-175401
device-2017-05-28-175919

**Pull request merged**
