### PR TITLE
 Updating French strings.xml

### PR DESCRIPTION
**Pull request by H-F-M**
1-Correction about variable in "access_token_updated_for"
	Before:
	<string name="access_token_updated_for">"Le jeton d'accès a été mis à jour à %1%."</string>
	After:
	<string name="access_token_updated_for">L\'autorisation d\'accès a été mis à jour pour %1$s.</string>

2-  Updating French strings.xml v0.5.3, add some translations en corrections

### CODE REVIEW

**Comment by H-F-M** [comment]
i hope it's ok now ...

**Comment by tateisu** [comment]
these string resource is not found in default locale.
where these came from ?


```
	<string name="abc_action_bar_home_description">Revenir à l\'accueil</string>
	<string name="abc_action_bar_home_description_format">%1$s, %2$s</string>
	<string name="abc_action_bar_home_subtitle_description_format">%1$s, %2$s, %3$s</string>
	<string name="abc_action_bar_up_description">Revenir en haut de la page</string>
	<string name="abc_action_menu_overflow_description">Plus d\'options</string>
	<string name="abc_action_mode_done">OK</string>
	<string name="abc_activity_chooser_view_see_all">Tout afficher</string>
	<string name="abc_activitychooserview_choose_application">Sélectionner une application</string>
	<string name="abc_capital_off">DÉSACTIVÉ</string>
	<string name="abc_capital_on">ACTIVÉ</string>
	<string name="abc_search_hint">Rechercher…</string>
	<string name="abc_searchview_description_clear">Effacer la requête</string>
	<string name="abc_searchview_description_query">Requête de recherche</string>
	<string name="abc_searchview_description_search">Rechercher</string>
	<string name="abc_searchview_description_submit">Envoyer la requête</string>
	<string name="abc_searchview_description_voice">Recherche vocale</string>
	<string name="abc_shareactionprovider_share_with">Partager avec</string>
	<string name="abc_shareactionprovider_share_with_application">Partager avec %s</string>
	<string name="abc_toolbar_collapse_description">Réduire</string>
	<string name="search_menu_title">Rechercher</string>
	<string name="status_bar_notification_info_overflow">&gt;999</string>

```

**Comment by tateisu** [comment]
all other strings are merged.

**Comment by tateisu** [comment]
What is your Mastodon ID ? (@user@host) 
I'll add your id in "about this app".

**Pull request merged**
