### PR TITLE
French language update according v0.5.3

### PR DESCRIPTION
**Pull request by H-F-M**
I made some changes regarding sentences that did not correspond to their actions, some complements and corrections too. I added the new sentences arrived with v0.5.3

### CODE REVIEW

**Comment by H-F-M** [comment]
Please use the 2nd file (mistakes corrected)
95d3b7b

**Comment by tateisu** [comment]
you should not close before merge it...

**Comment by tateisu** [comment]
please make another pull request and don't close before merge

**Comment by H-F-M** [comment]
Mistake about me sorry, i have erased all and restarted to give you the
last version (and I'm not too used to github) if some problems apears, i
join the string.xml (last from 0.5.3) to this mail. Sorry!

2017-05-15 0:10 GMT+02:00 tateisu <notifications@github.com>:

**Pull request closed without merging**
