### PR TITLE
Display avatars as rounded rectangles

### PR DESCRIPTION
**Pull request by APerson241**

### CODE REVIEW

**Comment by tateisu** [comment]
I'm sorry. This app has been refactored with recent commit.
Can you fork the latest version again and create a smaller patch?

**Comment by APerson241** [comment]
I think this patch is already based on the latest version. I'm not sure if a smaller patch is possible - we have to create a new class to add rounded corners, since NetworkImageView can't have rounded corners, and the layout XML files will have to be edited anyway.

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/pull/7/commits/8cc13fd0d5e2d030ba63dbe98efe57726a4a3ba6
Your commit changes 150 files +5596-2471 line.

I can not review it before merge.

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/pull/7/files

- dark theme is not supported 
- in light theme, background color is NOT #ffffff .

I think more better way is customize NetworkImageView and apply BitmapShader, os just using RoundedBitmapDrawable .

**Comment by tateisu** [comment]
I've implement using RoundedBitmapDrawable.
https://github.com/tateisu/SubwayTooter/commit/2188825925afb59f6e2f23c71d95555c868932da

**Pull request closed without merging**
